import React from "react";
import Dashboard from "./components/Dashboard/Dashboard";

export const metadata = {
  title: "Propertics | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {

  return (
    <>
      <Dashboard component={children} />
    </>
  );
}